global:
  scrape_interval: 5s # Scrape nhanh để test realtime

scrape_configs:
  - job_name: 'nestjs-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:9464']